spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db  # Ensure the database exists
    username: root  # Replace with your MySQL username
    password: root  # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-1
      maximum-pool-size: 10  # Adjust based on your needs
      minimum-idle: 5  # Adjust based on your needs

  # Configure JPA settings
  jpa:
    hibernate:
      ddl-auto: update  # Automatically updates the schema (use 'create' for a fresh schema)
      dialect: org.hibernate.dialect.MySQL5Dialect  # Use the MySQL dialect
    show-sql: true  # Show SQL queries in the console
    properties:
      hibernate:
        format_sql: true  # Format SQL for better readability

  # Optional: Enable Spring Data JPA repositories
  data:
    jpa:
      repositories:
        enabled: true

logging:
  level:
    org.hibernate: INFO  # Log Hibernate-related information
    org.springframework: INFO  # Log Spring framework-related information

server:
  port: 8080  # Configure server port if needed

# Optional: Configure Flyway or Liquibase if you're using database migrations
# spring:
#   flyway:
#     enabled: true
#     locations: classpath:db/migration  # Your migrations folder if using Flyway
#   liquibase:
#     enabled: false  # Set true if you're using Liquibase instead of Flyway
